In [24]:
import pandas as pd
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
NVIDIA GeForce RTX 4060 Ti

In [25]:
dataset = pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [26]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [27]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [28]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [29]:
dependent = dataset[["charges"]]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(independent,dependent, test_size=0.30, random_state=0)

In [31]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {
    'criterion':['squared_error','friedman_mse',
              'absolute_error','poisson'
             ],
    'max_features':['sqrt','log2',None ]
}
grid = GridSearchCV(RandomForestRegressor(),param_grid, refit=True,verbose=3, n_jobs=1)


grid.fit(X_train,y_train,)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5] END criterion=squared_error, max_features=sqrt;, score=0.864 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=sqrt;, score=0.787 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END criterion=squared_error, max_features=sqrt;, score=0.810 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=sqrt;, score=0.828 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=sqrt;, score=0.764 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END criterion=squared_error, max_features=log2;, score=0.859 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=log2;, score=0.785 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=log2;, score=0.813 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END criterion=squared_error, max_features=log2;, score=0.828 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=log2;, score=0.773 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=None;, score=0.860 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END criterion=squared_error, max_features=None;, score=0.764 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=None;, score=0.813 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END criterion=squared_error, max_features=None;, score=0.801 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=None;, score=0.770 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=sqrt;, score=0.865 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END criterion=friedman_mse, max_features=sqrt;, score=0.790 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=sqrt;, score=0.804 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=sqrt;, score=0.828 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END criterion=friedman_mse, max_features=sqrt;, score=0.771 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=log2;, score=0.865 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=log2;, score=0.789 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END criterion=friedman_mse, max_features=log2;, score=0.804 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=log2;, score=0.826 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=log2;, score=0.775 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END criterion=friedman_mse, max_features=None;, score=0.864 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=None;, score=0.766 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END criterion=friedman_mse, max_features=None;, score=0.812 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=None;, score=0.804 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END criterion=friedman_mse, max_features=None;, score=0.771 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END criterion=absolute_error, max_features=sqrt;, score=0.861 total time=   0.2s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END criterion=absolute_error, max_features=sqrt;, score=0.799 total time=   0.2s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END criterion=absolute_error, max_features=sqrt;, score=0.809 total time=   0.2s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END criterion=absolute_error, max_features=sqrt;, score=0.818 total time=   0.2s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END criterion=absolute_error, max_features=sqrt;, score=0.768 total time=   0.2s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END criterion=absolute_error, max_features=log2;, score=0.860 total time=   0.2s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END criterion=absolute_error, max_features=log2;, score=0.796 total time=   0.2s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END criterion=absolute_error, max_features=log2;, score=0.813 total time=   0.2s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END criterion=absolute_error, max_features=log2;, score=0.821 total time=   0.2s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END criterion=absolute_error, max_features=log2;, score=0.769 total time=   0.2s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END criterion=absolute_error, max_features=None;, score=0.856 total time=   0.4s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END criterion=absolute_error, max_features=None;, score=0.776 total time=   0.4s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END criterion=absolute_error, max_features=None;, score=0.797 total time=   0.4s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END criterion=absolute_error, max_features=None;, score=0.795 total time=   0.4s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END criterion=absolute_error, max_features=None;, score=0.766 total time=   0.4s
[CV 1/5] END criterion=poisson, max_features=sqrt;, score=0.857 total time=   0.0s
[CV 2/5] END criterion=poisson, max_features=sqrt;, score=0.789 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END criterion=poisson, max_features=sqrt;, score=0.809 total time=   0.0s
[CV 4/5] END criterion=poisson, max_features=sqrt;, score=0.837 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END criterion=poisson, max_features=sqrt;, score=0.768 total time=   0.0s
[CV 1/5] END criterion=poisson, max_features=log2;, score=0.864 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END criterion=poisson, max_features=log2;, score=0.790 total time=   0.0s
[CV 3/5] END criterion=poisson, max_features=log2;, score=0.811 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END criterion=poisson, max_features=log2;, score=0.830 total time=   0.0s
[CV 5/5] END criterion=poisson, max_features=log2;, score=0.763 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END criterion=poisson, max_features=None;, score=0.865 total time=   0.0s
[CV 2/5] END criterion=poisson, max_features=None;, score=0.767 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END criterion=poisson, max_features=None;, score=0.814 total time=   0.0s
[CV 4/5] END criterion=poisson, max_features=None;, score=0.799 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END criterion=poisson, max_features=None;, score=0.775 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2', None]},
             verbose=3)

In [32]:
re = grid.cv_results_
print("The R_Score value for best parameter {}:".format(grid.best_params_))

The R_Score value for best parameter {'criterion': 'poisson', 'max_features': 'sqrt'}:

In [33]:
table = pd.DataFrame.from_dict(re)

In [34]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.081220,0.001659,0.004001,0.000002,squared_error,sqrt,"{'criterion': 'squared_error', 'max_features':...",0.863573,0.786797,0.809902,0.827844,0.764343,0.810492,0.034089,8
1,0.081142,0.001066,0.004601,0.000800,squared_error,log2,"{'criterion': 'squared_error', 'max_features':...",0.858965,0.784737,0.813072,0.828480,0.772718,0.811594,0.030868,6
2,0.110323,0.000815,0.004400,0.000490,squared_error,None,"{'criterion': 'squared_error', 'max_features':...",0.859603,0.763568,0.812619,0.800776,0.770305,0.801374,0.034386,11
3,0.080787,0.000628,0.004201,0.000400,friedman_mse,sqrt,"{'criterion': 'friedman_mse', 'max_features': ...",0.864871,0.790340,0.804324,0.828486,0.771166,0.811837,0.032442,3
4,0.079405,0.000584,0.004101,0.000489,friedman_mse,log2,"{'criterion': 'friedman_mse', 'max_features': ...",0.864825,0.788958,0.803599,0.826018,0.774721,0.811624,0.031552,4
5,0.109296,0.002212,0.004201,0.000400,friedman_mse,None,"{'criterion': 'friedman_mse', 'max_features': ...",0.864143,0.765979,0.811802,0.804188,0.770931,0.803409,0.035258,10
6,0.291320,0.004979,0.004202,0.000399,absolute_error,sqrt,"{'criterion': 'absolute_error', 'max_features'...",0.860855,0.799294,0.808544,0.818027,0.768433,0.811031,0.029966,7
7,0.291828,0.003235,0.004401,0.000489,absolute_error,log2,"{'criterion': 'absolute_error', 'max_features'...",0.860414,0.796232,0.812775,0.821461,0.768632,0.811903,0.030211,2
8,0.507370,0.002325,0.004401,0.000490,absolute_error,None,"{'criterion': 'absolute_error', 'max_features'...",0.855862,0.775948,0.796599,0.795342,0.766377,0.798025,0.031123,12
9,0.098113,0.001623,0.003997,0.000006,poisson,sqrt,"{'criterion': 'poisson', 'max_features': 'sqrt'}",0.857495,0.789019,0.808820,0.837132,0.767794,0.812052,0.032230,1
10,0.097375,0.000661,0.004501,0.000633,poisson,log2,"{'criterion': 'poisson', 'max_features': 'log2'}",0.863546,0.790320,0.811108,0.829718,0.763359,0.811610,0.034079,5
11,0.129438,0.000864,0.004200,0.000399,poisson,None,"{'criterion': 'poisson', 'max_features': None}",0.865056,0.766543,0.813928,0.798850,0.775179,0.803911,0.034890,9

In [35]:
y_pred = grid.predict(X_test)

In [36]:
y_pred

array([10786.8089685 ,  9157.5246878 , 43865.0509135 , 13664.369491  ,
       10214.1655937 , 11155.5261087 ,  2279.415926  , 12209.8111729 ,
        7384.3045015 ,  5716.6096188 ,  5958.0182289 , 14471.6473297 ,
        8613.3665352 ,  6362.7353691 , 22701.8847473 , 11757.5913341 ,
       13862.1434841 ,  4056.4035852 ,  6818.6781342 , 32885.1484551 ,
       24800.1013282 , 16437.8434578 , 10340.2210494 , 27811.5913035 ,
        4173.1131166 ,  6534.434916  ,  4760.2854034 ,  8198.0233575 ,
        3674.248751  , 10651.1767625 ,  7949.646079  , 45735.8354613 ,
       15269.8854955 , 12982.6773871 , 19225.0932554 ,  4233.8205562 ,
        9387.3347333 , 37527.264768  , 38733.8882625 ,  2619.9699886 ,
        6119.1967363 ,  3444.6355727 , 19660.7506457 , 46510.4438494 ,
       36676.58723033,  3558.880483  , 11936.8867842 ,  7201.0135551 ,
        5959.7146744 , 13496.431966  ,  3590.7146824 ,  4253.9900163 ,
       26409.9221264 , 45380.8749479 , 11602.634015  ,  9051.6783776 ,
        6151.7632222 , 11860.2687428 , 10258.1186665 , 14497.3823975 ,
        2208.9561751 , 44231.5752221 , 15958.7627061 , 17739.4143456 ,
       11681.8199352 , 10320.1574598 , 31099.6445034 , 39381.1686907 ,
        3541.5427593 ,  9334.8277216 , 15093.1928752 , 12603.023218  ,
       17456.8513858 , 14998.8208867 , 13453.6081303 , 13811.2498164 ,
        9739.5873334 , 14677.3765324 , 19994.7187855 , 44442.5320115 ,
       11566.7514505 , 47211.6555901 ,  4039.4879478 , 10457.6534218 ,
       40178.9411251 , 19649.739419  ,  5009.3729359 ,  3681.1103804 ,
       13191.2435862 , 37286.0469533 ,  6806.0484234 , 15976.8964704 ,
        3487.8385679 ,  9950.533807  ,  9737.6800734 ,  4811.4941534 ,
       42261.0547996 , 40233.9439472 ,  5241.1154882 , 11152.3257297 ,
        3210.1321661 ,  7435.5964944 ,  6942.7738018 , 37502.0385487 ,
       26498.3231309 ,  5110.9336339 , 11161.1058607 ,  4040.100819  ,
       11744.1446395 , 43748.9021766 , 11356.9025329 ,  8429.7036065 ,
        9578.9446189 , 34113.2280876 , 44788.2522674 ,  8362.6885633 ,
        3073.121207  , 11602.6017298 , 16559.8571998 , 10759.5817459 ,
       41711.6576274 , 11211.7863121 , 14160.324558  ,  9410.3214164 ,
       10953.7226234 ,  5374.6540809 , 24595.3235421 , 24643.5633259 ,
       47198.2903888 ,  1786.5749811 , 11716.4629039 ,  3569.5212368 ,
        7397.6765487 ,  9225.2253206 , 34513.5195417 , 34035.4459823 ,
       25267.8965482 , 12306.7893721 , 24431.6520117 ,  6170.1001158 ,
        2023.3542875 , 13329.2145681 ,  9524.7245843 , 11850.8575046 ,
        6197.7323319 , 13891.6225675 , 19773.8859003 , 11941.2953057 ,
        1695.4347615 , 11084.4748092 ,  6191.050401  , 38328.2658649 ,
        9597.3561229 ,  6825.9679455 ,  3352.2683992 ,  6845.2683518 ,
        3609.5388023 ,  6162.9730708 , 11757.5913341 , 10078.3310795 ,
        6313.7581205 , 12921.083091  , 13557.601196  ,  9381.3288207 ,
        4685.5268965 ,  7498.0290493 , 17550.600733  ,  7961.4879412 ,
        5041.3442362 ,  2182.94313825,  8130.9289443 ,  5759.28519   ,
       10359.5637421 ,  3946.2743645 ,  7313.5716344 ,  7233.1210183 ,
        4758.3427655 ,  6458.7722017 , 31595.1625592 ,  2042.5834293 ,
       14565.0514398 ,  6890.0028768 , 11276.366898  ,  6044.009996  ,
        8370.2023089 , 27779.2338494 ,  4240.1742244 ,  3269.2875991 ,
       13973.4284592 , 10722.6002005 , 41082.3789117 ,  7604.0206887 ,
        5512.054155  , 27916.2035806 ,  4204.1797302 ,  3121.6932249 ,
        8660.3395594 ,  6443.781679  , 10598.8470735 ,  4650.5098144 ,
       12059.8652778 , 43767.8115464 , 17242.8742248 , 19083.9944557 ,
       11699.7942656 , 43936.2409749 ,  4339.0049294 , 10355.3829225 ,
       10077.69192   ,  3194.4187045 ,  8679.103046  , 13882.8003036 ,
        7157.2264734 ,  4624.0838437 ,  6510.1185409 ,  3916.0084905 ,
        6673.5076402 ,  6241.0572024 , 14046.3337517 ,  6734.440027  ,
       10186.8529538 ,  8363.7441377 , 10406.1240458 ,  8907.837701  ,
       12670.615331  , 14601.17117   , 18787.1863137 , 12541.043909  ,
        6895.7284308 ,  2730.9912442 ,  5842.6261985 ,  8469.6220412 ,
       14331.9695209 ,  6177.0837766 ,  5827.1076654 ,  7624.4982078 ,
       12204.7120215 , 33141.9291766 ,  5875.340654  , 11236.4547653 ,
        7062.0535146 , 36982.2853225 , 10234.7357496 ,  8543.6365816 ,
       10324.7764695 , 10644.5299766 ,  3358.0618572 ,  8346.3549991 ,
        4472.2598011 ,  6394.8875619 , 18732.949815  , 44305.8211472 ,
        5373.7563381 ,  5189.6374204 ,  7768.0683874 ,  1796.6231815 ,
        8227.267488  ,  3856.11457695,  5780.0988408 , 10535.0163669 ,
        9145.7169488 , 25092.5438624 , 43375.3667908 , 16118.0887752 ,
        6383.0438231 , 11135.3663455 , 40911.4833094 , 11001.2997004 ,
       38908.995275  ,  1532.1868275 , 36807.8145919 ,  5141.0575162 ,
       12107.251928  ,  6633.1394654 , 38802.1472591 ,  5551.0801727 ,
        9674.6885745 ,  9996.2817295 ,  4801.1366033 , 17351.4009702 ,
       12171.4804073 , 11443.5889316 , 15012.9426478 , 14055.096501  ,
        8168.6217233 ,  4351.4689226 ,  9902.0341429 , 22757.5726527 ,
        5434.6077408 ,  1874.2282804 ,  2752.0197205 , 45780.2488237 ,
       10236.6338024 ,  4624.9426576 , 16418.9899855 , 14678.2284381 ,
       33987.0632292 ,  6836.2329573 ,  5809.2907079 ,  8688.313523  ,
        3585.2429502 ,  5148.8759647 , 19270.896369  , 17639.0570008 ,
       13702.5196334 ,  2811.3881652 ,  3711.4854453 , 10381.4747135 ,
       11142.671711  , 17917.5699947 , 20613.1914095 ,  7192.8155067 ,
       18391.3554366 ,  2432.8135681 ,  7665.7145742 ,  9674.6422849 ,
       16723.856169  ,  2941.4051395 ,  9349.7149612 , 45349.3938074 ,
        4596.1389178 ,  5466.6465088 ,  2124.4520085 , 14096.9549833 ,
        4023.8749751 , 12307.3904879 , 43184.4158596 , 19068.1460262 ,
        9015.1202788 , 41133.2802749 , 18897.2898574 , 11330.5061351 ,
       10648.7467132 ,  4338.4249785 , 27962.0054351 ,  4717.2479712 ,
       14991.1414695 ,  2852.0626744 , 18063.2383496 ,  4094.648245  ,
       26841.6140704 ,  9699.0838943 ,  4187.915298  , 38981.4526712 ,
        7120.8794042 ,  5241.8284435 , 32105.3316995 ,  2933.1448174 ,
       11062.88777   ,  3482.6586261 , 11712.6628283 ,  4189.6656018 ,
        7123.0587322 ,  8193.0257946 , 42535.3465495 , 10593.3710883 ,
       33615.2999122 , 38186.234042  ,  5921.6245634 ,  9986.4815497 ,
        2006.0331128 ,  5208.0084078 ,  4607.5423442 ,  9629.7766448 ,
       44559.3130934 , 11276.7883445 ,  2174.916141  , 13206.3309202 ,
        2083.343203  , 13757.3386115 ,  9337.5443815 ,  2929.0897497 ,
        4336.237601  , 35626.5295335 ,  6752.6201193 ,  2125.860992  ,
       39853.8381952 , 12994.578873  , 42289.4392837 , 11554.2504231 ,
        7439.8961871 ,  3012.7812233 ,  2165.9574515 , 13112.8499991 ,
        5414.3749829 ,  2028.7526    , 11390.4464994 ,  7157.866016  ,
        7568.6223461 ,  8578.3023907 ,  8078.3215396 , 40543.7486712 ,
        6272.0465019 , 15036.5173192 ,  7583.99281084, 17234.0145451 ,
       11114.1107102 ,  7973.5853776 , 18002.9068722 , 12369.3216929 ,
       16751.207782  , 19606.1287533 ])

In [37]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test, y_pred)
r_score

0.8702149616342431

In [38]:
prediction = grid.predict([[22,34,0,1,1]])
print('prediction={}'.format(prediction))

prediction=[34363.1599158]

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(