In [2]:
import pandas as pd
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
NVIDIA GeForce RTX 4060 Ti

In [3]:
dataset = pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [7]:
dependent = dataset[["charges"]]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(independent,dependent, test_size=0.30, random_state=0)

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {
    'criterion':['squared_error','friedman_mse',
              'absolute_error','poisson'
             ],
    'splitter':['best','random' ]
}
grid = GridSearchCV(DecisionTreeRegressor(),param_grid, refit=True,verbose=3, n_jobs=1)


grid.fit(X_train,y_train,)

Fitting 5 folds for each of 8 candidates, totalling 40 fits
[CV 1/5] END criterion=squared_error, splitter=best;, score=0.751 total time=   0.0s
[CV 2/5] END criterion=squared_error, splitter=best;, score=0.548 total time=   0.0s
[CV 3/5] END criterion=squared_error, splitter=best;, score=0.772 total time=   0.0s
[CV 4/5] END criterion=squared_error, splitter=best;, score=0.638 total time=   0.0s
[CV 5/5] END criterion=squared_error, splitter=best;, score=0.660 total time=   0.0s
[CV 1/5] END criterion=squared_error, splitter=random;, score=0.626 total time=   0.0s
[CV 2/5] END criterion=squared_error, splitter=random;, score=0.600 total time=   0.0s
[CV 3/5] END criterion=squared_error, splitter=random;, score=0.680 total time=   0.0s
[CV 4/5] END criterion=squared_error, splitter=random;, score=0.648 total time=   0.0s
[CV 5/5] END criterion=squared_error, splitter=random;, score=0.638 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, splitter=best;, score=0.732 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, splitter=best;, score=0.562 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, splitter=best;, score=0.774 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, splitter=best;, score=0.618 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, splitter=best;, score=0.661 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, splitter=random;, score=0.670 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, splitter=random;, score=0.669 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, splitter=random;, score=0.665 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, splitter=random;, score=0.621 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, splitter=random;, score=0.588 total time=   0.0s
[CV 1/5] END criterion=absolute_error, splitter=best;, score=0.752 total time=   0.0s
[CV 2/5] END criterion=absolute_error, splitter=best;, score=0.637 total time=   0.0s
[CV 3/5] END criterion=absolute_error, splitter=best;, score=0.607 total time=   0.0s
[CV 4/5] END criterion=absolute_error, splitter=best;, score=0.543 total time=   0.0s
[CV 5/5] END criterion=absolute_error, splitter=best;, score=0.666 total time=   0.0s
[CV 1/5] END criterion=absolute_error, splitter=random;, score=0.669 total time=   0.0s
[CV 2/5] END criterion=absolute_error, splitter=random;, score=0.668 total time=   0.0s
[CV 3/5] END criterion=absolute_error, splitter=random;, score=0.692 total time=   0.0s
[CV 4/5] END criterion=absolute_error, splitter=random;, score=0.666 total time=   0.0s
[CV 5/5] END criterion=absolute_error, splitter=random;, score=0.587 total time=   0.0s
[CV 1/5] END ..criterion=poisson, splitter=best;, score=0.698 total time=   0.0s
[CV 2/5] END ..criterion=poisson, splitter=best;, score=0.574 total time=   0.0s
[CV 3/5] END ..criterion=poisson, splitter=best;, score=0.725 total time=   0.0s
[CV 4/5] END ..criterion=poisson, splitter=best;, score=0.551 total time=   0.0s
[CV 5/5] END ..criterion=poisson, splitter=best;, score=0.616 total time=   0.0s
[CV 1/5] END criterion=poisson, splitter=random;, score=0.661 total time=   0.0s
[CV 2/5] END criterion=poisson, splitter=random;, score=0.674 total time=   0.0s
[CV 3/5] END criterion=poisson, splitter=random;, score=0.627 total time=   0.0s
[CV 4/5] END criterion=poisson, splitter=random;, score=0.690 total time=   0.0s
[CV 5/5] END criterion=poisson, splitter=random;, score=0.610 total time=   0.0s

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [10]:
re = grid.cv_results_
print("The R_Score value for best parameter {}:".format(grid.best_params_))

The R_Score value for best parameter {'criterion': 'squared_error', 'splitter': 'best'}:

In [11]:
table = pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001801,4.000669e-04,0.000800,3.999710e-04,squared_error,best,"{'criterion': 'squared_error', 'splitter': 'be...",0.750787,0.548045,0.771615,0.638092,0.659566,0.673621,0.080977,1
1,0.001500,4.473421e-04,0.000800,3.999949e-04,squared_error,random,"{'criterion': 'squared_error', 'splitter': 'ra...",0.625821,0.600292,0.680237,0.647812,0.637752,0.638383,0.026267,7
2,0.002001,8.176054e-07,0.001000,3.371748e-07,friedman_mse,best,"{'criterion': 'friedman_mse', 'splitter': 'best'}",0.732492,0.562316,0.773751,0.617644,0.661361,0.669513,0.076263,2
3,0.001400,4.898625e-04,0.000800,4.000187e-04,friedman_mse,random,"{'criterion': 'friedman_mse', 'splitter': 'ran...",0.669556,0.669287,0.664793,0.620826,0.587740,0.642441,0.032909,5
4,0.009200,3.999710e-04,0.000600,4.899403e-04,absolute_error,best,"{'criterion': 'absolute_error', 'splitter': 'b...",0.752107,0.637052,0.606960,0.543368,0.666214,0.641140,0.068828,6
5,0.006801,7.486724e-04,0.000901,4.906718e-04,absolute_error,random,"{'criterion': 'absolute_error', 'splitter': 'r...",0.669205,0.668433,0.691992,0.665856,0.586943,0.656486,0.036026,3
6,0.001999,4.156970e-07,0.001001,5.722046e-07,poisson,best,"{'criterion': 'poisson', 'splitter': 'best'}",0.697605,0.573843,0.725479,0.550817,0.615630,0.632675,0.068236,8
7,0.001400,4.900767e-04,0.000599,4.894733e-04,poisson,random,"{'criterion': 'poisson', 'splitter': 'random'}",0.660754,0.673849,0.626954,0.689705,0.609622,0.652177,0.029660,4

In [13]:
y_pred = grid.predict(X_test)

In [14]:
y_pred

array([10085.846   ,  8930.93455 , 44202.6536  , 13143.86485 ,
        9264.797   ,  7228.21565 ,  1615.7667  , 10381.4787  ,
        7954.517   ,  5253.524   ,  4766.022   , 30284.64294 ,
        7633.7206  ,  4992.3764  , 18246.4955  , 11015.1747  ,
       12124.9924  ,  3292.52985 ,  6455.86265 , 33307.5508  ,
       24667.419   , 11987.1682  ,  9625.92    , 24915.22085 ,
        1391.5287  ,  4151.0287  ,  3558.62025 ,  8538.28845 ,
        3353.284   ,  8116.26885 ,  7954.517   , 48673.5588  ,
       13981.85035 , 10713.644   , 15817.9857  ,  3554.203   ,
        8733.22925 , 44585.45587 , 39597.4072  ,  1880.07    ,
        4766.022   ,  2866.091   , 21659.9301  , 44400.4064  ,
       36307.7983  ,  2719.27975 , 11015.1747  ,  6272.4772  ,
        4719.52405 , 11830.6072  ,  2473.3341  ,  2331.519   ,
       24915.22085 , 60021.39897 , 11856.4115  , 19673.33573 ,
        3021.80915 ,  8442.667   ,  7726.854   , 12913.9924  ,
        1252.407   , 46130.5265  , 14590.63205 , 25333.33284 ,
       19144.57652 ,  9875.6804  , 33307.5508  , 39047.285   ,
        2913.569   , 15828.82173 , 24513.09126 , 10436.096   ,
       16297.846   , 13981.85035 , 12629.8967  , 12233.828   ,
        6250.435   ,  8116.26885 , 19539.243   , 46599.1084  ,
       11286.5387  , 46113.511   ,  1526.312   ,  6849.026   ,
       39125.33225 , 20984.0936  ,  3227.1211  ,  2727.3951  ,
       12913.9924  , 36950.2567  ,  6128.79745 , 10796.35025 ,
        3201.24515 ,  8516.829   , 14358.36437 ,  4076.497   ,
       41999.52    , 62592.87309 ,  4949.7587  , 11090.7178  ,
        1981.5819  ,  5373.36425 ,  4922.9159  , 39047.285   ,
       37829.7242  ,  3558.62025 , 12029.2867  , 19673.33573 ,
       11743.9341  , 45008.9555  , 12094.478   ,  4753.6368  ,
        8930.93455 , 33750.2918  , 47269.854   ,  7256.7231  ,
        2221.56445 ,  8442.667   , 36910.60803 ,  9225.2564  ,
       40273.6455  , 10197.7722  , 14901.5167  ,  5253.524   ,
        7624.63    ,  4719.73655 , 38245.59327 , 35069.37452 ,
       48673.5588  ,  1534.3045  ,  8522.003   ,  3443.064   ,
        5974.3847  ,  8688.85885 , 62592.87309 , 37079.372   ,
       21259.37795 , 10156.7832  , 22218.1149  , 12609.88702 ,
        2130.6759  , 10965.446   ,  8978.1851  , 10601.63225 ,
       11737.84884 , 14901.5167  , 36910.60803 , 22395.74424 ,
        1628.4709  , 10791.96    ,  5974.3847  , 38126.2465  ,
        9288.0267  , 21344.8467  ,  1633.0444  ,  6393.60345 ,
        1526.312   , 11272.33139 , 11015.1747  ,  9414.92    ,
        4449.462   , 13405.3903  , 12815.44495 ,  8798.593   ,
        4134.08245 , 24671.66334 , 20167.33603 ,  5693.4305  ,
        4239.89265 ,  2217.46915 ,  4449.462   ,  4438.2634  ,
        8522.003   ,  2416.955   , 18804.7524  , 24671.66334 ,
        3847.674   ,  7077.1894  , 27533.9129  ,  1705.6245  ,
       25992.82104 ,  6313.759   , 11945.1327  , 19673.33573 ,
        7228.21565 , 27808.7251  ,  1526.312   ,  2585.269   ,
       14901.5167  ,  9563.029   , 40974.1649  ,  3877.30425 ,
        5266.3656  , 21978.6769  ,  3021.80915 ,  3044.2133  ,
       20420.60465 ,  5989.52365 ,  3471.4096  ,  4527.18295 ,
       10923.9332  , 47055.5321  , 11987.1682  , 20745.9891  ,
        4449.462   , 42111.6647  ,  3309.7926  , 10564.8845  ,
        5375.038   ,  1146.7966  ,  8871.1517  , 13880.949   ,
        4340.4409  ,  2855.43755 ,  6272.4772  , 25081.76784 ,
        6548.19505 ,  7228.21565 , 14001.1338  ,  6933.24225 ,
        5989.52365 ,  8252.2843  ,  8930.93455 ,  3176.8159  ,
       12231.6136  , 14410.9321  , 33471.97189 , 11931.12525 ,
       13725.47184 ,  2523.1695  , 21344.8467  ,  8083.9198  ,
       21797.0004  , 24671.66334 ,  4032.2407  ,  7256.7231  ,
        9447.25035 , 34806.4677  ,  5488.262   , 12094.478   ,
        5649.715   , 37484.4493  ,  7265.7025  ,  7419.4779  ,
        7441.501   , 10085.846   ,  2304.0022  ,  7345.7266  ,
        1515.3449  ,  6272.4772  , 19719.6947  , 47291.055   ,
        3877.30425 ,  3227.1211  ,  2200.83085 ,  1704.70015 ,
        7147.4728  ,  2211.13075 , 24671.66334 , 23288.9284  ,
        8891.1395  , 24393.6224  , 46599.1084  , 16455.70785 ,
        6272.4772  , 10982.5013  , 44585.45587 ,  9225.2564  ,
       39047.285   ,  1137.011   , 37484.4493  ,  5152.134   ,
       11946.6259  ,  3309.7926  , 39047.285   ,  5012.471   ,
       10072.05505 ,  9225.2564  ,  1980.07    , 12913.9924  ,
       12224.35085 , 14358.36437 , 12146.971   , 21344.8467  ,
        6373.55735 ,  4466.6214  ,  8965.79575 , 21880.82    ,
        3227.1211  ,  1705.6245  ,  3077.0955  , 47896.79135 ,
        9617.66245 ,  4149.736   , 11987.1682  , 10923.9332  ,
       36898.73308 ,  6389.37785 ,  4747.0529  ,  9386.1613  ,
        1639.5631  ,  1980.07    , 32734.1863  , 15817.9857  ,
       13352.0998  ,  2523.1695  ,  2727.3951  , 10096.97    ,
       10564.8845  , 13747.87235 , 20745.9891  ,  4795.6568  ,
       15518.18025 ,  2459.7201  , 28476.73499 , 14358.36437 ,
        7742.1098  ,  3077.0955  ,  7419.4779  , 44202.6536  ,
        2020.177   ,  4922.9159  ,  1731.677   ,  8280.6227  ,
       19673.33573 , 11931.12525 , 47055.5321  , 16776.30405 ,
        9288.0267  , 41949.2441  , 11987.1682  ,  4449.462   ,
        9288.0267  ,  4466.6214  , 27218.43725 ,  4350.5144  ,
       13415.0381  ,  2221.56445 , 15518.18025 ,  3176.8159  ,
       24869.8368  , 28476.73499 ,  2842.76075 , 44501.3982  ,
        5693.4305  ,  5266.3656  , 27533.9129  ,  1639.5631  ,
        7726.854   ,  1842.519   , 10269.46    ,  3208.787   ,
        6666.243   ,  5253.524   , 43921.1837  ,  6250.435   ,
       62592.87309 , 37484.4493  ,  5488.262   , 15828.82173 ,
        1252.407   ,  3558.62025 ,  3056.3881  ,  8068.185   ,
       43813.8661  , 11830.6072  ,  1731.677   , 12124.9924  ,
        2166.732   , 17929.30337 ,  4438.2634  ,  2416.955   ,
        2897.3235  , 36307.7983  ,  6933.24225 ,  2196.4732  ,
       39774.2763  , 10923.9332  , 41661.602   , 11931.12525 ,
        4151.0287  ,  2775.19215 ,  1906.35825 , 25333.33284 ,
        4747.0529  ,  2207.69745 , 10959.6947  ,  7954.517   ,
        5966.8874  ,  3877.30425 , 13126.67745 , 44585.45587 ,
        1526.312   ,  8601.3293  ,  7882.429475, 28476.73499 ,
       11090.7178  ,  3766.8838  , 18223.4512  , 10713.644   ,
       16085.1275  , 12957.118   ])

In [15]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test, y_pred)
r_score

0.6935407981017487

In [16]:
prediction = grid.predict([[22,34,0,1,1]])
print('prediction={}'.format(prediction))

prediction=[34779.615]

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(