In [ ]:
!pip install pandas

In [1]:
import pandas as pd
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
NVIDIA GeForce RTX 4060 Ti

In [2]:
dataset = pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [6]:
dependent = dataset[["charges"]]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(independent,dependent, test_size=0.30, random_state=0)

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {
    'kernel':['rbf','poly',
              # 'sigmoid','linear'
             ],
    'C':[10,100
         # 1000, 2000,3000
        ],
    'gamma':['auto','scale']
}
grid = GridSearchCV(SVR(),param_grid, refit=True,verbose=3, n_jobs=1)


grid.fit(X_train,y_train,)

Fitting 5 folds for each of 8 candidates, totalling 40 fits
[CV 1/5] END .....C=10, gamma=auto, kernel=rbf;, score=-0.042 total time=   0.0s
[CV 2/5] END .....C=10, gamma=auto, kernel=rbf;, score=-0.036 total time=   0.0s
[CV 3/5] END .....C=10, gamma=auto, kernel=rbf;, score=-0.147 total time=   0.0s
[CV 4/5] END .....C=10, gamma=auto, kernel=rbf;, score=-0.140 total time=   0.0s
[CV 5/5] END .....C=10, gamma=auto, kernel=rbf;, score=-0.142 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 1/5] END .....C=10, gamma=auto, kernel=poly;, score=0.821 total time= 4.3min

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END .....C=10, gamma=auto, kernel=poly;, score=0.820 total time= 7.5min

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 3/5] END .....C=10, gamma=auto, kernel=poly;, score=0.815 total time= 2.9min

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 4/5] END .....C=10, gamma=auto, kernel=poly;, score=0.795 total time= 4.0min

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END .....C=10, gamma=auto, kernel=poly;, score=0.759 total time= 3.4min
[CV 1/5] END ....C=10, gamma=scale, kernel=rbf;, score=-0.045 total time=   0.0s
[CV 2/5] END ....C=10, gamma=scale, kernel=rbf;, score=-0.013 total time=   0.0s
[CV 3/5] END ....C=10, gamma=scale, kernel=rbf;, score=-0.152 total time=   0.0s
[CV 4/5] END ....C=10, gamma=scale, kernel=rbf;, score=-0.152 total time=   0.0s
[CV 5/5] END ....C=10, gamma=scale, kernel=rbf;, score=-0.139 total time=   0.0s
[CV 1/5] END ...C=10, gamma=scale, kernel=poly;, score=-0.134 total time=   0.0s
[CV 2/5] END ....C=10, gamma=scale, kernel=poly;, score=0.027 total time=   0.0s
[CV 3/5] END ...C=10, gamma=scale, kernel=poly;, score=-0.213 total time=   0.0s
[CV 4/5] END ...C=10, gamma=scale, kernel=poly;, score=-0.237 total time=   0.0s
[CV 5/5] END ...C=10, gamma=scale, kernel=poly;, score=-0.160 total time=   0.0s
[CV 1/5] END ....C=100, gamma=auto, kernel=rbf;, score=-0.040 total time=   0.0s
[CV 2/5] END ....C=100, gamma=auto, kernel=rbf;, score=-0.021 total time=   0.0s
[CV 3/5] END ....C=100, gamma=auto, kernel=rbf;, score=-0.141 total time=   0.0s
[CV 4/5] END ....C=100, gamma=auto, kernel=rbf;, score=-0.138 total time=   0.0s
[CV 5/5] END ....C=100, gamma=auto, kernel=rbf;, score=-0.134 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 1/5] END ....C=100, gamma=auto, kernel=poly;, score=0.714 total time= 9.5min

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END ....C=100, gamma=auto, kernel=poly;, score=0.531 total time= 7.8min

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 3/5] END ....C=100, gamma=auto, kernel=poly;, score=0.743 total time= 7.7min

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 4/5] END ....C=100, gamma=auto, kernel=poly;, score=0.698 total time= 3.1min

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END ....C=100, gamma=auto, kernel=poly;, score=0.646 total time= 5.6min
[CV 1/5] END ...C=100, gamma=scale, kernel=rbf;, score=-0.159 total time=   0.0s
[CV 2/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.014 total time=   0.0s
[CV 3/5] END ...C=100, gamma=scale, kernel=rbf;, score=-0.243 total time=   0.0s
[CV 4/5] END ...C=100, gamma=scale, kernel=rbf;, score=-0.255 total time=   0.0s
[CV 5/5] END ...C=100, gamma=scale, kernel=rbf;, score=-0.167 total time=   0.0s
[CV 1/5] END ..C=100, gamma=scale, kernel=poly;, score=-0.176 total time=   0.0s
[CV 2/5] END ...C=100, gamma=scale, kernel=poly;, score=0.037 total time=   0.0s
[CV 3/5] END ..C=100, gamma=scale, kernel=poly;, score=-0.230 total time=   0.0s
[CV 4/5] END ..C=100, gamma=scale, kernel=poly;, score=-0.265 total time=   0.0s
[CV 5/5] END ..C=100, gamma=scale, kernel=poly;, score=-0.171 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=1,
             param_grid={'C': [10, 100], 'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly']},
             verbose=3)

In [9]:
re = grid.cv_results_
print("The R_Score value for best parameter {}:".format(grid.best_params_))

The R_Score value for best parameter {'C': 10, 'gamma': 'auto', 'kernel': 'poly'}:

In [12]:
table = pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.012100,1.112792e-03,0.005001,9.464947e-07,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.041899,-0.035931,-0.147151,-0.139987,-0.142206,-0.101435,0.051135,5
1,264.743383,9.640759e+01,0.002001,8.203817e-07,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.820908,0.820234,0.815211,0.794673,0.758928,0.801991,0.023551,1
2,0.008300,3.998180e-04,0.004600,4.906421e-04,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.045477,-0.013336,-0.151791,-0.151967,-0.139448,-0.100404,0.059028,4
3,0.006999,6.217196e-07,0.002001,1.907349e-07,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",-0.134216,0.026782,-0.212979,-0.237453,-0.159582,-0.143490,0.092731,6
4,0.011701,3.995200e-04,0.005000,1.168008e-07,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",-0.040107,-0.020972,-0.140683,-0.137931,-0.133749,-0.094689,0.052772,3
5,405.259603,1.321584e+02,0.002001,7.008046e-07,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.713502,0.531256,0.742999,0.697659,0.645947,0.666273,0.074492,2
6,0.007999,8.064048e-07,0.004801,4.006636e-04,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",-0.158546,0.013775,-0.243127,-0.254520,-0.166782,-0.161840,0.095993,8
7,0.008500,8.949773e-04,0.001602,4.897847e-04,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",-0.176499,0.036989,-0.230291,-0.265222,-0.171039,-0.161212,0.105075,7

In [14]:
y_pred = grid.predict(X_test)
y_pred

array([ 9.42526319e+03,  8.27816046e+03,  4.96514104e+04,  1.29670685e+04,
        9.61481477e+03,  3.93201568e+03,  2.78671762e+03,  1.17238547e+04,
        7.00324691e+03,  5.49250373e+03,  5.71110167e+03,  1.00314788e+04,
        7.07094028e+03,  4.45196903e+03,  2.41530497e+04,  1.09442414e+04,
        1.24499563e+04,  3.38205486e+03,  6.00222103e+03,  2.59316329e+04,
        2.60367309e+04,  1.28760257e+04,  9.67539924e+03,  2.68483413e+04,
        2.12851618e+03,  4.35409967e+03,  3.69104295e+03,  7.69371342e+03,
        4.17436135e+03,  7.90214674e+03,  7.44741340e+03,  5.49114750e+04,
        1.34492014e+04,  1.01161809e+04,  1.42800353e+04,  4.05929358e+03,
        8.76591887e+03,  3.60666273e+04,  3.24391376e+04,  2.62494506e+03,
        4.92614125e+03,  3.26726887e+03,  2.34674496e+04,  4.71767973e+04,
        3.47336985e+04,  3.65303802e+03,  1.09413448e+04,  6.11210918e+03,
        4.20435171e+03,  1.26892742e+04,  2.93527581e+03,  3.80082771e+03,
        2.82493098e+04,  4.36080538e+04,  1.27056277e+04,  2.95417670e+03,
        2.62648702e+03,  7.90679256e+03,  1.01455684e+04,  1.33311808e+04,
        2.11029336e+03,  4.07659673e+04,  1.57748399e+04,  9.70774355e+03,
        1.16190125e+04,  1.01618730e+04,  2.51570566e+04,  3.35634072e+04,
        3.52054844e+03,  8.42585705e+03,  1.40885209e+04,  1.15979620e+04,
        2.15110369e+04,  1.51856990e+04,  1.37568726e+04,  1.35395805e+04,
        6.62107367e+03,  7.61483769e+03,  2.16202692e+04,  4.66451497e+04,
        1.14182624e+04,  5.85664674e+04,  2.24898910e+03,  7.05742384e+03,
        3.74255380e+04,  2.14755082e+04,  3.47244987e+03,  2.82523925e+03,
        1.26313999e+04,  3.48323757e+04,  6.08102214e+03,  9.87921976e+03,
        2.70363199e+03,  8.19587732e+03,  4.02364802e+03,  4.74614398e+03,
        3.40730576e+04,  3.06151246e+04,  5.09133645e+03,  1.07003101e+04,
        2.35470083e+03,  5.06298998e+03,  4.61398304e+03,  3.47006430e+04,
        2.79242031e+04,  3.62268230e+03,  1.05254917e+04,  3.70584481e+03,
        1.13388587e+04,  3.95019911e+04,  1.31953503e+04,  4.81494124e+03,
        8.61046212e+03,  2.69843064e+04,  5.60137772e+04,  6.83376548e+03,
        2.80108745e+03,  7.90715541e+03,  1.28506686e+04,  8.99665876e+03,
        3.98987559e+04,  1.00429554e+04,  1.58608793e+04,  5.68801637e+03,
        7.28591043e+03,  4.35496989e+03,  2.48262143e+04,  2.17071276e+04,
        5.23675429e+04,  1.66585071e+03,  7.94622868e+03,  2.22686790e+03,
        5.86526845e+03,  8.33940457e+03,  2.91171678e+04,  2.86185504e+04,
        2.18706846e+04,  1.00823203e+04,  2.31812245e+04,  3.05194898e+03,
        2.72160632e+03,  9.87394914e+03,  9.72754877e+03,  9.52427407e+03,
        4.42852751e+03,  1.57710787e+04,  1.36294568e+04,  3.73316736e+03,
        2.40062363e+03,  1.02224005e+04,  5.74953326e+03,  4.60011585e+04,
        9.12447139e+03,  2.45842039e+03,  2.39071980e+03,  6.29168404e+03,
        2.87830102e+03,  2.48835309e+03,  1.09438342e+04,  9.97610903e+03,
        4.90535495e+03,  1.35746770e+04,  1.36281280e+04,  9.57642638e+03,
        4.24608045e+03,  5.18618626e+03,  1.50283666e+04,  5.53775324e+03,
        4.01002062e+03,  1.51201570e+03,  4.20695663e+03,  4.15609822e+03,
        7.68443476e+03,  2.26984273e+03,  4.78799482e+03,  5.35934193e+03,
        4.00172667e+03,  5.31949200e+03,  3.75046864e+04,  2.15944407e+03,
        1.09536939e+04,  6.69987943e+03,  1.08489546e+04,  2.87257726e+03,
        4.91465318e+03,  3.15112090e+04,  2.27348584e+03,  3.30594451e+03,
        1.57723709e+04,  9.81161706e+03,  3.41057134e+04,  4.25381277e+03,
        5.29632070e+03,  2.31487215e+04,  2.45068500e+03,  2.72462282e+03,
        5.81732156e+03,  6.24307904e+03,  4.61932404e+03,  4.05093229e+03,
        1.10757550e+04,  4.32444918e+04,  1.23538814e+04,  2.17658211e+04,
        4.47228110e+03,  4.07639455e+04,  3.72411220e+03,  8.79395430e+03,
        5.97533748e+03, -2.55317231e+01,  8.07584213e+03,  1.45764864e+04,
        4.83977654e+03,  3.02444596e+03,  5.94892032e+03,  2.75961901e+03,
        6.24771528e+03,  4.66360467e+03,  1.56866699e+04,  5.87725559e+03,
        6.55368956e+03,  6.99661958e+03,  8.16668688e+03,  3.43690620e+03,
        1.24034441e+04,  1.45829283e+04,  1.30481638e+04,  1.25473143e+04,
        6.44977587e+03,  2.82604547e+03,  1.89548629e+03,  7.85360011e+03,
        1.29479104e+04,  4.14376663e+03,  4.53609354e+03,  6.88962953e+03,
        8.58513040e+03,  2.71893819e+04,  5.25405918e+03,  1.14583222e+04,
        5.43020788e+03,  3.24613310e+04,  7.47711547e+03,  6.58709218e+03,
        8.23240975e+03,  9.85632637e+03,  3.32918284e+03,  7.26031937e+03,
        3.16741291e+03,  5.81167364e+03,  2.40101868e+04,  4.09645642e+04,
        4.33402249e+03,  3.28861600e+03,  2.65968194e+03,  2.29416842e+03,
        7.22524069e+03,  1.95978906e+03,  4.89503845e+03,  3.85749758e+03,
        8.62100149e+03,  2.77120737e+04,  3.91841777e+04,  1.62603238e+04,
        5.93417059e+03,  1.11411293e+04,  4.01317740e+04,  8.97459464e+03,
        3.51830624e+04,  1.46412041e+03,  3.46668140e+04,  5.11329718e+03,
        1.30040402e+04,  4.04555511e+03,  3.59836046e+04,  5.14239294e+03,
        9.08738629e+03,  1.09092565e+04,  2.58481982e+03,  1.41409587e+04,
        1.24595715e+04,  4.01513390e+03,  1.22520439e+04,  2.60354296e+03,
        5.59965041e+03,  4.29909552e+03,  9.23777156e+03,  2.26374009e+04,
        2.50927460e+03,  2.19257599e+03,  3.07725776e+03,  4.59484282e+04,
        8.21952595e+03,  4.60425664e+03,  1.23781006e+04,  1.15314912e+04,
        2.74526159e+04,  6.21250855e+03,  4.76168134e+03,  8.16413643e+03,
        1.97892262e+03,  3.24436789e+03,  1.14264996e+04,  1.92254603e+04,
        1.46170321e+04,  2.81898652e+03,  3.72348140e+03,  8.71573032e+03,
        8.76293591e+03,  1.48976606e+04,  2.50446719e+04,  6.37981056e+03,
        1.58712123e+04,  2.69133287e+03,  5.34199890e+03,  4.02553577e+03,
        7.80375525e+03,  3.02009048e+03,  5.79168085e+03,  4.42118389e+04,
        3.76064731e+03,  3.99490037e+03,  2.94455911e+03,  8.27517202e+03,
        3.84652175e+03,  1.27127366e+04,  4.31702855e+04,  1.80201834e+04,
        8.36710887e+03,  4.31594433e+04,  1.33978311e+04,  4.48538180e+03,
        9.03549908e+03,  4.38415843e+03,  3.38279133e+04,  4.69673608e+03,
        1.45643438e+04,  2.70791478e+03,  1.80733964e+04,  3.52665369e+03,
        2.88890315e+04,  5.84940073e+03,  2.75665748e+03,  4.55459075e+04,
        5.38408842e+03,  5.00435480e+03,  3.76854117e+04,  1.99338781e+03,
        8.06609441e+03,  3.14860910e+03,  1.29131914e+04,  3.68009735e+03,
        5.76179225e+03,  5.34812343e+03,  3.88522836e+04,  8.17249836e+03,
        2.72556906e+04,  3.65858402e+04,  5.26269686e+03,  9.70674567e+03,
        2.16167016e+03,  3.64996597e+03,  3.44018408e+03,  8.32201880e+03,
        4.05740823e+04,  1.09172738e+04,  2.91220618e+03,  1.18853425e+04,
        2.56577076e+03,  7.32617778e+03,  3.77544205e+03,  1.37447948e+03,
        3.39035061e+03,  3.49609225e+04,  5.72882730e+03,  2.89416083e+03,
        3.94330074e+04,  1.07567908e+04,  3.89155902e+04,  1.14470164e+04,
        4.31952282e+03,  2.72098143e+03,  2.87483196e+03,  1.01220585e+04,
        4.65157502e+03,  2.47542507e+03,  1.01822055e+04,  6.88804208e+03,
        5.55829023e+03,  4.23891680e+03,  3.21265047e+03,  3.88838698e+04,
        2.17684282e+03,  8.87160299e+03,  1.77470672e+03,  7.25857354e+03,
        1.06611112e+04,  3.62238177e+03,  1.92067316e+04,  1.01651247e+04,
        1.56968835e+04,  1.48981308e+04])

In [15]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test, y_pred)
r_score

0.8651026640939162