In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [6]:
dependent = dataset[["charges"]]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(independent,dependent, test_size=0.30, random_state=0)

In [8]:
from sklearn.ensemble import AdaBoostRegressor
regressor = AdaBoostRegressor( n_estimators=100,random_state=0)
regressor.fit(X_train,y_train,)

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

AdaBoostRegressor(n_estimators=100, random_state=0)

In [9]:
y_pred = regressor.predict(X_test)
y_pred

array([15585.43998096, 13599.0517963 , 46261.53943   , 14444.51254404,
       12907.00232984,  6912.31668256,  5791.61329319, 15585.43998096,
        8687.92288728,  8687.92288728,  6912.31668256, 15585.43998096,
       13599.0517963 ,  6912.31668256, 19817.40194324, 15585.43998096,
       14444.51254404,  8687.92288728,  6912.31668256, 37907.74005909,
       26387.57288333, 16708.77857483, 14444.51254404, 26387.57288333,
        8687.92288728,  8687.92288728,  6912.31668256,  8687.92288728,
        6912.31668256, 13599.0517963 ,  6912.31668256, 46261.53943   ,
       14444.51254404, 14444.51254404, 19817.40194324,  6912.31668256,
       13599.0517963 , 37907.74005909, 43046.68604803,  8687.92288728,
        6912.31668256,  6912.31668256, 19817.40194324, 46261.53943   ,
       37907.74005909,  8687.92288728, 15585.43998096,  6912.31668256,
        6912.31668256, 16708.77857483,  8687.92288728,  5791.61329319,
       26387.57288333, 46261.53943   , 14444.51254404,  8687.92288728,
        8687.92288728, 12907.00232984, 13599.0517963 , 16708.77857483,
        5791.61329319, 46261.53943   , 16708.77857483, 15585.43998096,
       13599.0517963 , 15585.43998096, 37427.68127192, 43046.68604803,
        5791.61329319,  8687.92288728, 14444.51254404, 16708.77857483,
       19235.18177276, 14444.51254404, 14444.51254404, 14444.51254404,
       12907.00232984, 13599.0517963 , 19817.40194324, 46261.53943   ,
       14444.51254404, 46261.53943   ,  8687.92288728, 13599.0517963 ,
       46261.53943   , 19817.40194324,  8687.92288728,  8687.92288728,
       16708.77857483, 37907.74005909,  8687.92288728, 14444.51254404,
        8687.92288728, 13599.0517963 ,  8687.92288728,  8687.92288728,
       46261.53943   , 46261.53943   ,  8687.92288728, 14444.51254404,
        8687.92288728,  8687.92288728,  8687.92288728, 43046.68604803,
       26387.57288333,  6912.31668256, 14444.51254404,  8687.92288728,
       14444.51254404, 46261.53943   , 15585.43998096,  8687.92288728,
       13599.0517963 , 37907.74005909, 46261.53943   ,  6912.31668256,
        5791.61329319, 12907.00232984, 16708.77857483, 13599.0517963 ,
       46261.53943   , 14444.51254404, 14444.51254404,  8687.92288728,
       13599.0517963 ,  6912.31668256, 26387.57288333, 26387.57288333,
       46261.53943   ,  8687.92288728, 13599.0517963 ,  8687.92288728,
        8687.92288728, 12907.00232984, 27563.07714242, 43046.68604803,
       26387.57288333, 15585.43998096, 26387.57288333,  5791.61329319,
        8687.92288728, 14444.51254404, 13599.0517963 , 14444.51254404,
        6912.31668256, 14444.51254404, 16708.77857483,  5791.61329319,
        5791.61329319, 15585.43998096,  6912.31668256, 37907.74005909,
       15585.43998096,  8687.92288728,  8687.92288728,  8687.92288728,
        8687.92288728,  5791.61329319, 15585.43998096, 13599.0517963 ,
        8687.92288728, 14444.51254404, 14444.51254404, 15585.43998096,
        6912.31668256,  8687.92288728, 19235.18177276,  8687.92288728,
        6912.31668256,  8687.92288728,  8687.92288728,  6912.31668256,
       13599.0517963 ,  8687.92288728,  8687.92288728,  8687.92288728,
        6912.31668256,  6912.31668256, 26387.57288333,  5791.61329319,
       15585.43998096,  8687.92288728, 14444.51254404,  8687.92288728,
        6912.31668256, 26387.57288333,  8687.92288728,  5791.61329319,
       14444.51254404, 13599.0517963 , 46261.53943   ,  8687.92288728,
        6912.31668256, 26387.57288333,  8687.92288728,  6912.31668256,
        8687.92288728,  8687.92288728,  8687.92288728,  6912.31668256,
       15585.43998096, 46261.53943   , 16708.77857483, 19817.40194324,
        8687.92288728, 46261.53943   ,  6912.31668256, 14444.51254404,
        8687.92288728,  8687.92288728, 13599.0517963 , 14444.51254404,
        6912.31668256,  8687.92288728,  6912.31668256,  6912.31668256,
        6912.31668256,  6912.31668256, 16708.77857483,  6912.31668256,
        8687.92288728,  6912.31668256, 12907.00232984,  6912.31668256,
       14444.51254404, 14444.51254404, 16708.77857483, 14444.51254404,
        6912.31668256,  6912.31668256,  8687.92288728, 13599.0517963 ,
       14444.51254404,  8687.92288728,  6912.31668256,  8687.92288728,
       13599.0517963 , 37907.74005909,  6912.31668256, 15585.43998096,
        6912.31668256, 37907.74005909,  8687.92288728, 12907.00232984,
       13599.0517963 , 15585.43998096,  5791.61329319, 13599.0517963 ,
        5791.61329319,  6912.31668256, 19817.40194324, 46261.53943   ,
        8687.92288728,  8687.92288728,  5791.61329319,  5791.61329319,
       13599.0517963 ,  8687.92288728,  6912.31668256,  6912.31668256,
       13599.0517963 , 26387.57288333, 46261.53943   , 16708.77857483,
        6912.31668256, 14444.51254404, 37907.74005909, 13599.0517963 ,
       43046.68604803,  8687.92288728, 37907.74005909,  8687.92288728,
       16708.77857483,  6912.31668256, 43046.68604803,  8687.92288728,
       14444.51254404, 13599.0517963 ,  8687.92288728, 16708.77857483,
       14444.51254404,  8687.92288728, 14444.51254404,  8687.92288728,
        8687.92288728,  8687.92288728,  8687.92288728, 26387.57288333,
        8687.92288728,  5791.61329319,  5791.61329319, 46261.53943   ,
       13599.0517963 ,  8687.92288728, 16708.77857483, 16708.77857483,
       37907.74005909,  6912.31668256,  8687.92288728, 12907.00232984,
        8687.92288728,  8687.92288728, 19817.40194324, 19817.40194324,
       14444.51254404,  6912.31668256,  8687.92288728, 13599.0517963 ,
       14444.51254404, 19235.18177276, 19817.40194324,  8687.92288728,
       19235.18177276,  8687.92288728,  8687.92288728,  8687.92288728,
       12907.00232984,  5791.61329319, 12907.00232984, 46261.53943   ,
        8687.92288728,  8687.92288728,  5791.61329319, 12907.00232984,
        8687.92288728, 14444.51254404, 46261.53943   , 19817.40194324,
       13599.0517963 , 46261.53943   , 16708.77857483,  8687.92288728,
       15585.43998096,  8687.92288728, 26387.57288333,  6912.31668256,
       14444.51254404,  5791.61329319, 19235.18177276,  6912.31668256,
       26387.57288333,  8687.92288728,  6912.31668256, 37907.74005909,
        8687.92288728,  6912.31668256, 26387.57288333,  8687.92288728,
       13599.0517963 ,  5791.61329319, 13599.0517963 ,  6912.31668256,
        8687.92288728,  8687.92288728, 46261.53943   , 12907.00232984,
       37427.68127192, 37907.74005909,  6912.31668256,  8687.92288728,
        5791.61329319,  6912.31668256,  8687.92288728, 13599.0517963 ,
       46261.53943   , 14444.51254404,  5791.61329319, 14444.51254404,
        8687.92288728, 12907.00232984,  6912.31668256,  8687.92288728,
        6912.31668256, 37907.74005909,  6912.31668256,  5791.61329319,
       44851.74645036, 16708.77857483, 46261.53943   , 14444.51254404,
        8687.92288728,  5791.61329319,  5791.61329319, 15585.43998096,
        6912.31668256,  8687.92288728, 15585.43998096,  6912.31668256,
        6912.31668256,  6912.31668256,  5791.61329319, 37907.74005909,
        8687.92288728, 12907.00232984,  8687.92288728,  8687.92288728,
       14444.51254404,  8687.92288728, 19235.18177276, 14444.51254404,
       16708.77857483, 14444.51254404])

In [10]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test, y_pred)
r_score

0.8447476929154872