In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [6]:
dependent = dataset[["charges"]]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(independent,dependent, test_size=0.30, random_state=0)

In [9]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.1.1-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\python312\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\admin\appdata\roaming\python\python312\site-packages (from xgboost) (1.16.0)
Downloading xgboost-3.1.1-py3-none-win_amd64.whl (72.0 MB)
   ---------------------------------------- 0.0/72.0 MB ? eta -:--:--
   ------ --------------------------------- 12.6/72.0 MB 60.7 MB/s eta 0:00:01
   ------------- -------------------------- 24.4/72.0 MB 59.4 MB/s eta 0:00:01
   ------------------- -------------------- 35.9/72.0 MB 58.5 MB/s eta 0:00:01
   -------------------------- ------------- 48.0/72.0 MB 58.8 MB/s eta 0:00:01
   --------------------------------- ------ 59.8/72.0 MB 58.6 MB/s eta 0:00:01
   ---------------------------------------  71.6/72.0 MB 58.5 MB/s eta 0:00:01
   ---------------------------------------- 72.0/72.0 MB 51.0 MB/s  0:00:01
Installing collected packages: xgboost
Successfully installed xgboost-3.1.1

WARNING: Ignoring invalid distribution ~ (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorflow-intel (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorflow-intel (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorflow-intel (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)

In [10]:
import xgboost as xgb
regressor =  xgb.XGBRegressor(objective='reg:squarederror',  # Objective for regression
                           n_estimators=100,
                           learning_rate=0.1,
                           max_depth=5,
                           random_state=42)
regressor.fit(X_train,y_train,)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [13]:
regressor.intercept_

array([13232.916], dtype=float32)

In [14]:
y_pred = regressor.predict(X_test)
y_pred

array([11054.513 ,  9942.801 , 44618.516 , 12877.586 ,  9860.077 ,
        4414.183 ,  1800.9082, 12130.995 ,  7548.834 ,  6302.4805,
        6795.113 , 17189.615 ,  9123.5   ,  6588.4653, 28260.406 ,
       12714.615 , 13864.373 ,  4060.2493,  6453.7163, 34642.652 ,
       24289.674 , 14787.684 , 10916.924 , 30682.457 ,  3367.8562,
        6028.1445,  5788.156 ,  7573.5996,  3758.5557,  9790.362 ,
        6914.4917, 47365.21  , 15374.667 , 11868.568 , 17155.797 ,
        4837.0537, 10648.285 , 36235.145 , 38656.156 ,  3328.5513,
        5431.568 ,  5313.9766, 19219.172 , 47507.69  , 38436.023 ,
        4050.125 , 12714.615 ,  6921.6   ,  4793.9224, 12397.408 ,
        2840.5273,  3883.742 , 27235.594 , 46197.34  , 11216.853 ,
        5362.699 ,  4049.784 , 10792.029 , 10154.281 , 18269.01  ,
        2141.1655, 45168.53  , 17942.617 , 15077.324 , 12029.985 ,
        9303.239 , 38411.082 , 38131.848 ,  3360.7559,  8857.694 ,
       15312.296 , 11755.104 , 16526.357 , 14494.82  , 13862.166 ,
       14574.521 ,  8881.172 ,  9795.296 , 19453.5   , 48717.543 ,
       11234.054 , 49305.98  ,  3413.8557, 10051.448 , 41007.176 ,
       19579.678 ,  5166.235 ,  3937.0825, 15364.274 , 39848.715 ,
        5850.791 , 11881.408 ,  6093.4297,  9852.516 ,  5339.406 ,
        4987.4355, 42382.258 , 47173.516 ,  6042.852 , 10779.824 ,
        3376.0305,  6233.3926,  7534.9624, 38503.133 , 26649.709 ,
        3373.244 , 11100.8125,  4273.0356, 17649.629 , 45264.668 ,
       12396.114 ,  5948.174 ,  9911.998 , 34606.3   , 47261.89  ,
        7372.7935,  2344.1587, 10792.029 , 18268.658 , 10724.697 ,
       41393.574 , 11110.164 , 14121.759 , 10590.837 , 11854.517 ,
        6051.1606, 28778.576 , 27460.355 , 47787.695 ,  2383.5178,
       12522.616 ,  4275.435 ,  6494.484 ,  9668.078 , 45108.15  ,
       38211.043 , 22656.893 , 14957.259 , 23762.191 ,  6266.8765,
        2852.4163, 12300.652 , 17610.646 , 11329.963 ,  5686.577 ,
       15122.245 , 18248.723 ,  8223.489 ,  2120.3625, 12072.897 ,
        7528.6772, 38442.902 , 10836.23  , 10556.535 ,  4197.038 ,
        9654.759 ,  3932.6729,  3686.0408, 12714.615 , 11989.131 ,
        7059.348 , 13558.571 , 13259.401 ,  9029.413 ,  4174.241 ,
        9298.775 , 15788.704 ,  6527.7544,  5666.6997,  2387.072 ,
        7842.056 ,  8310.37  ,  9462.954 ,  2265.3687,  8216.505 ,
        9520.746 ,  5530.726 ,  6772.2104, 26325.734 ,  1649.674 ,
       15349.175 ,  6840.1934, 11262.578 ,  4931.189 ,  6306.2563,
       28190.867 ,  3415.0352,  4120.515 , 14255.934 , 12059.274 ,
       41038.37  ,  5197.2227,  5595.879 , 24425.418 ,  3217.251 ,
        4549.838 ,  7422.0103,  7107.8306,  6164.68  ,  5192.763 ,
       12413.756 , 47294.316 , 14930.6045, 19099.443 ,  7839.044 ,
       42921.527 ,  4792.398 , 10781.17  ,  7766.15  ,  1798.281 ,
        9985.802 , 14496.025 ,  7086.137 ,  3585.7852,  6277.5225,
        5062.2476,  6324.164 ,  6714.3057, 15451.27  ,  8893.092 ,
        9490.248 , 11989.507 ,  9909.8   ,  3551.2847, 13568.6455,
       13831.754 , 24262.955 , 12070.362 ,  6170.0283,  2789.0366,
        9908.422 ,  8939.094 , 12624.312 ,  8634.933 ,  4806.2915,
        7671.5684, 14323.878 , 35051.7   ,  6553.242 , 15522.489 ,
        9842.856 , 39362.297 ,  8129.5493, 10848.41  ,  9423.014 ,
       11119.648 ,  3213.026 ,  8900.525 ,  2497.721 ,  6367.248 ,
       19659.52  , 45646.055 ,  5208.541 ,  5166.235 ,  2653.403 ,
        2673.9216, 10164.739 ,  2382.6973,  8954.352 , 10074.956 ,
        8289.288 , 26772.637 , 45434.73  , 17397.371 ,  6700.5474,
       10779.824 , 44179.902 ,  9922.868 , 41209.816 ,  2216.205 ,
       39177.105 ,  6097.6377, 11910.177 ,  6428.04  , 40088.57  ,
        6105.816 , 10492.892 , 10008.996 ,  3907.7769, 18828.229 ,
       12475.777 ,  6006.3535, 15891.246 ,  9978.687 ,  7141.4834,
        4693.037 ,  8598.395 , 22744.793 ,  2874.1458,  1538.3207,
        2272.0186, 49329.836 , 10719.135 ,  4944.75  , 14980.087 ,
       12070.024 , 34786.527 ,  8841.801 ,  5836.5156, 10207.84  ,
        3321.8184,  3910.674 , 22804.533 , 16314.277 , 14582.792 ,
        2962.503 ,  4141.398 , 12846.717 , 11139.369 , 15861.0625,
       20160.34  ,  9489.232 , 16355.137 ,  2935.7832,  9663.334 ,
        5339.406 , 12633.587 ,  2528.6638,  8548.966 , 45099.285 ,
        4511.845 ,  6274.691 ,  2555.0686, 10653.471 ,  4190.721 ,
       12807.406 , 47483.82  , 17598.14  ,  9861.22  , 45228.63  ,
       15254.93  ,  7837.8643, 10981.15  ,  5051.165 , 28153.078 ,
        4905.6367, 14561.526 ,  3051.581 , 15871.265 ,  3419.2346,
       24434.242 ,  9519.487 ,  5062.2476, 41846.105 ,  6869.9985,
        5073.369 , 30796.2   ,  3706.8047, 10155.937 ,  3597.4304,
       12152.896 ,  3330.9768,  7871.986 ,  6620.413 , 46179.887 ,
       11404.146 , 40506.395 , 39057.1   ,  6553.242 , 10387.819 ,
        2821.9553,  5923.1353,  3675.797 ,  9644.998 , 47243.86  ,
       10736.925 ,  2192.2693, 15528.076 ,  2791.5557, 12315.408 ,
        6276.593 ,  3300.7546,  4389.0215, 35895.652 ,  7803.9346,
        2082.8306, 42454.684 , 11845.527 , 42494.637 , 12111.39  ,
        5404.3994,  3452.4558,  2079.3855, 14709.836 ,  6105.4873,
        2824.5378, 11581.522 ,  6744.944 ,  6604.5522,  5088.2163,
        5119.6772, 43439.656 ,  3367.3926, 11698.206 ,  5821.8174,
       11713.193 , 10779.824 ,  4958.397 , 19344.002 , 10683.091 ,
       16247.939 , 18364.469 ], dtype=float32)

In [15]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test, y_pred)
r_score

0.8661189675331116