In [54]:
import pandas as pd

In [55]:
dataset = pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [56]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [57]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [58]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [59]:
dependent = dataset[["charges"]]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [60]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(independent,dependent, test_size=0.30, random_state=0)

In [228]:
from sklearn.svm import SVR
regressor = SVR(kernel='linear', C=500, gamma='auto')
regressor.fit(X_train,y_train,)

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=500, gamma='auto', kernel='linear')

In [229]:
regressor.intercept_

array([-4310.19119793])

In [230]:
regressor.n_support_

array([936])

In [231]:
y_pred = regressor.predict(X_test)
y_pred

array([10266.61434936,  9240.8862827 , 25837.02208164, 12449.7403859 ,
        9626.29445671,  4890.35746199,  1093.83319182, 11265.73869244,
        7675.00391747,  5525.50176618,  6343.64211527, 10355.98297573,
        8195.16881016,  5014.84792375, 19190.19428774, 10800.96413817,
       11842.995247  ,  3441.34863127,  6936.37772241, 17390.78477078,
       26247.28399714, 12128.81677801, 10202.99098   , 24784.68934565,
        2016.10001728,  5147.15090647,  3520.77922937,  8272.19343969,
        4520.33464268,  8818.99879023,  8167.32742088, 28364.41832126,
       12690.54934779, 10835.54380928, 18519.80696676,  4308.9660248 ,
        9270.39136994, 20044.84060015, 23847.99158727,  1793.09068362,
        5700.4135522 ,  3726.8235392 , 22315.18127394, 28395.71974143,
       17329.21071204,  2838.21733325, 10792.93495346,  7525.55687265,
        4561.12509934, 11756.27500666,  2625.12810635,  2591.11860844,
       25133.52550157, 27260.97059652, 12059.40129612,  3644.53014865,
        3114.8587708 ,  9247.31467573,  9361.98419842, 12240.77453557,
        1098.78292033, 29704.1802138 , 13250.201397  , 10186.18203496,
       10533.33431609, 10545.97075304, 17115.54763801, 21585.45376538,
        2575.6873233 ,  8300.53705794, 12519.78478907, 11534.89263668,
       17308.42480011, 13259.55316749, 12153.7935379 , 12239.31652077,
        8088.70199964,  8559.09010103, 22480.58384666, 28775.96336006,
       11210.7523065 , 24173.03446605,  1975.71078497,  8414.04189713,
       23979.60226958, 21760.46655603,  4000.20006874,  3008.89786317,
       12053.49347193, 20149.60377738,  6255.81920644, 10655.49542432,
        3311.61189516,  9071.88962759,  5213.95793767,  5323.88614315,
       26653.64703192, 24526.21985852,  5487.06083985, 11173.18960524,
        2251.3128807 ,  6120.24075343,  4698.5756616 , 21716.35517149,
       24348.70740141,  3357.82902854, 10730.36790168,  3946.08271167,
       11570.25778067, 28028.37284412, 11696.80349568,  5183.1417707 ,
        9493.61736737, 16886.90410754, 27859.19946055,  7918.71329727,
        1598.19863538,  9251.93753967, 12287.06975512,  9365.85968781,
       24799.73501817,  9897.88196007, 13593.54933402,  5415.71450064,
        8401.42794681,  4652.64540498, 25140.98451309, 24613.13611298,
       28201.12197024,  1826.62917597,  8855.41152852,  1355.26647601,
        6891.12415449,  9414.88774049, 23196.4886939 , 21098.72772448,
       23066.07526912, 10290.77626334, 26649.95010797,  2522.57168254,
        1759.51409291, 10600.62932863, 10048.29262282, 10460.7934475 ,
        5382.90546131, 13502.79521566, 12590.69044145,  3136.38055127,
         929.80507795, 10680.59247445,  6807.79094929, 19521.82394815,
       10053.05595384,  1264.26904901,  2079.86616353,  7399.01941011,
        2354.99861779,  1248.21067954, 10799.99090367, 10147.02863142,
        4503.87184782, 12752.10643078, 12197.71074533, 10233.10433881,
        4657.98074615,  4133.11726568, 17225.25134758,  5829.36576116,
        4628.24018239,  1422.42149439,  4119.96115107,  4234.37128054,
        8612.04782606,  2596.25793551,  4448.27582626,  4398.50039902,
        4125.733978  ,  6622.95994771, 28884.79483977,   771.47774107,
       11019.35244487,  7108.79814699, 11284.80168548,  3336.68965967,
        5711.3417908 , 28409.13934144,  1966.46505709,  2287.6402261 ,
       13429.68097285, 10264.68716593, 25358.11817825,  4094.33018916,
        6245.2729066 , 24648.64172405,  2855.19339021,  2351.48945542,
        6685.59310676,  6499.6695262 ,  4749.87568381,  4669.84595784,
       11164.74816303, 29113.26300585, 11838.7378189 , 21378.88473992,
        4614.59608646, 25396.58022714,  3391.87158679,  9963.72542584,
        6620.73438152,  1182.30436   ,  9259.09633146, 12870.32594234,
        4933.70313213,  2589.48339229,  7321.36585932,  2293.09538462,
        6763.24482061,  5359.70758565, 13174.81382061,  6698.21667363,
        6805.9285091 ,  7770.92259118,  9096.32469606,  2877.06268497,
       11845.04639457, 13232.14284845, 12218.59766188, 11652.83257819,
        7136.10378752,  2614.68281112,   869.16615535,  8903.14731422,
       12160.79441398,  2807.45624045,  5131.91563538,  7801.87008152,
        9456.63445586, 18458.64332853,  6508.54981824, 11089.84536691,
        6418.16249977, 18704.3170989 ,  8238.8238962 ,  7680.11476274,
        8678.225936  , 10554.62518511,  2351.75021273,  8309.03724821,
        2076.16876667,  7203.11786595, 20696.74608194, 29921.02511275,
        4198.46628207,  3728.97752832,  1163.17615088,   695.20048609,
        8499.19991704,  1350.15883176,  4229.0359394 ,  3797.94401843,
        8969.94147537, 25970.83215815, 28538.57953174, 13635.83590386,
        7311.75516851, 11437.35619546, 21751.91496551,  9342.74536812,
       23564.09634849,   973.54555689, 19443.65577117,  5492.98380287,
       12225.67242481,  3753.52138102, 22132.86922443,  5894.7983335 ,
       10161.4687605 ,  9861.85026932,  1851.11795454, 12665.07630159,
       11700.76437795,  5241.69512129, 11972.43543728,  1186.29047058,
        6728.13585531,  3448.05706721,  8835.21554829, 24061.56879553,
        3782.95394543,   755.29771728,  1697.62647147, 29095.7640702 ,
        9366.57216503,  5086.9701193 , 11857.22927465, 11431.71280242,
       18519.87354691,  7340.38203069,  5774.80908137,  9485.51382286,
        1144.76825109,  2218.11870161, 19763.7718399 , 19416.68613891,
       12826.28708057,  2626.36162528,  3488.10198625,  9143.90714462,
        9943.04419243, 16959.62490561, 22095.33175144,  6563.17307818,
       17507.42277629,  1460.18940592,  6972.55818522,  5202.64408646,
        8720.23613682,  1461.31871921,  7385.49649562, 24261.28891797,
        3149.0991801 ,  4021.42299356,  1266.02912051,  9204.11041842,
        4229.22737489, 11593.70858148, 29826.82841217, 20645.64943305,
        9500.63521923, 24452.80723292, 12405.02714532,  4623.84181434,
        9997.82489521,  3555.11286368, 28520.00452001,  5276.44096061,
       12369.90667401,  1396.80567129, 17556.08450195,  3111.66727682,
       27446.44382125,  7028.31395946,  2299.29975463, 19193.80812863,
        5574.56655314,  5854.79287688, 29734.0236191 ,  1140.14538715,
        8611.19440889,  1859.4267093 , 11422.86693486,  3450.32256871,
        6190.90309723,  5273.13564445, 26207.5521679 ,  8947.90643278,
       21799.88439077, 18486.60500804,  6514.51087964,  8932.92093838,
        1077.73672398,  3421.81919778,  2258.05941503,  9365.42220204,
       27270.31869308, 11033.95048968,  1319.1920558 , 11587.58776743,
        2116.62457915,  8404.55469758,  4149.78527079,  2478.80644819,
        3360.0835494 , 17278.68607329,  6633.58013446,   959.40517466,
       22443.02114538, 11120.67120293, 26211.46255462, 11288.871352  ,
        5061.62792359,  1914.45208478,  1687.85970187, 10486.88301776,
        5692.08414774,  1230.20767799, 10598.4588366 ,  7621.23271061,
        7142.01113883,  4080.58325164,  2461.01643653, 21005.9895116 ,
        1690.25468978,  9545.33926363,  1382.2755707 ,  8208.49571057,
       11156.15800126,  4082.82032384, 19125.26578131, 10859.38805488,
       13660.45736986, 12706.57923546])

In [232]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test, y_pred)
r_score

0.62704627619341